<<<<<<< HEAD
# Generated by Django 5.2.15 on 2026-07-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('country_code', models.CharField(default='+91', max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('organization_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('trainer', 'Trainer'), ('admin', 'Administrator')], max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
=======
# Generated by Django 5.2.15 on 2026-07-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('country_code', models.CharField(default='+91', max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('organization_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('trainer', 'Trainer'), ('admin', 'Administrator')], max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
>>>>>>> d0b9c95965475f9b14f001bb4aef49392b2e69f7
