# Generated by Django 5.2 on 2026-07-22 04:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('placementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementOfficerlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_id', models.CharField(max_length=20, unique=True)),
                ('registered_on', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('organization_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('designation', models.CharField(choices=[('', 'Select Specific Role'), ('professor', 'Professor'), ('trainer', 'Trainer'), ('admin', 'Administrator')], max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('RECRUITER', 'Recruiter'), ('TRAINING_COORDINATOR', 'Training Coordinator'), ('PLACEMENT_OFFICER', 'Placement Officer')], default='STUDENT', max_length=50)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='commonlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('student', 'Student'), ('recruiter', 'Recruiter'), ('placement_officer', 'Placement Officer'), ('training_coordinator', 'Training Coordinator')], max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='+1', max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('institution_name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('StudentProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='placementapp.studentregistration')),
            ],
        ),
    ]
